dev:
  postgres:
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: "postgres"
    password: "Dharmavaram1@"
    driver: "org.postgresql.Driver"
    port: 5432

  oracle:
    username: "test123"
    password: "oracle_password"
    connection_string: "jdbc:oracle:thin:@//dev-db-host:1521/ORCL"

  adls:
    account_name: "myadlsdevaccount"
    account_key: "myadlsdevkey"

qa:
  postgres:
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: "postgres"
    password: "Dharmavaram1@"
    driver: "org.postgresql.Driver"
    port: 5432

  sqlserver:
    url: "jdbc:sqlserver://decautoserver.database.windows.net:1433;database=decauto"
    user: "decadmin"
    password: "Dharmavaram1@"
    driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"

  adls:
    adls_account_name: "decautoadls"
    adls_container_name: "test"
    key: "vnH8MP/h4VB5vbfsP1x9rAZ5PiyMkIk5RBPnxCbrAjupr7GXMiCv0fHDuySVA036WYaKQDVXcMzz+AStHfeBKQ=="  # Your Account Key



prod:
  postgres:
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: "postgres"
    password: "Dharmavaram1@"
    driver: "org.postgresql.Driver"
    port: 5432
  oracle:
    username: "oracle_user"
    password: "oracle_password"
    connection_string: "jdbc:oracle:thin:@//dev-db-host:1521/ORCL"
  snowflake:
    url: "jdbc:snowflake://tqtrcxi-cw03901.snowflakecomputing.com"
    user: "KSREENIVASULU"
    password: "Dharmavaram@2024"
    database: "TEST_DB"
    schema: "TEST_SCHEMA"
    driver: "net.snowflake.client.jdbc.SnowflakeDriver"